# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-FillInForm
version:      1.06
version_from: lib/HTML/FillInForm.pm
installdirs:  site
requires:
    HTML::Parser:                  3.26
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
